-- 코드를 입력하세요
# SELECT
# r.FOOD_TYPE,
# r.REST_ID,
# r.REST_NAME,
# r.FAVORITES
# FROM
# REST_INFO AS R 
# JOIN (
#     SELECT
#     FOOD_TYPE,
#     MAX(FAVORITES) FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
#     ORDER BY FOOD_TYPE DESC
# ) AS S
# ON r.FOOD_TYPE = s.FOOD_TYPE AND r.FAVORITES = s.FAVORITES
# ORDER BY r.FOOD_TYPE DESC;

SELECT R.FOOD_TYPE	
,R.REST_ID
,R.REST_NAME
,R.FAVORITES
FROM REST_INFO AS R
JOIN (
   SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FAVORITES
) AS I

ON R.FOOD_TYPE = I.FOOD_TYPE AND R.FAVORITES = I.FAVORITES
ORDER BY R.FOOD_TYPE DESC
